INSERT INTO animais (nome, sexo, porte, idade, cor, raca, localizacao, descricao, status) VALUES
('Thor', 'macho', 'grande', 'adulto', 'preto', 'Labrador', 'Ceilândia, Brasília, DF', 'Muito brincalhão e enérgico, adora correr atrás de bolinhas.', 'D'),
('Luna', 'fêmea', 'pequeno', 'filhote', 'branco', 'Poodle', 'Asa Sul, Brasília, DF', 'Dócil, tímida no começo, mas muito carinhosa quando ganha confiança.', 'D'),
('Mel', 'fêmea', 'médio', 'adulto', 'marrom', 'Vira-lata', 'Taguatinga, Brasília, DF', 'Super dócil, se dá bem com gatos e outros cães.', 'I'),
('Rex', 'macho', 'grande', 'idoso', 'capa preta', 'Pastor Alemão', 'Guará, Brasília, DF', 'Calmo, companheiro e ótimo cão de guarda. Precisa de espaço.', 'D'),
('Pipoca', 'fêmea', 'pequeno', 'filhote', 'caramelo', 'Vira-lata', 'Samambaia, Brasília, DF', 'Energia pura! Adora roer brinquedos e brincar com crianças.', 'D'),
('Bob', 'macho', 'médio', 'adulto', 'preto e branco', 'Border Collie', 'Águas Claras, Brasília, DF', 'Extremamente inteligente e ativo. Precisa de tutores que pratiquem atividades.', 'D'),
('Amora', 'fêmea', 'pequeno', 'adulto', 'preto', 'Pinscher', 'Gama, Brasília, DF', 'Pequena no tamanho, mas com grande personalidade. Muito protetora.', 'D'),
('Fred', 'macho', 'médio', 'idoso', 'cinza', 'Vira-lata', 'Planaltina, Brasília, DF', 'Tranquilo, passa a maior parte do dia dormindo. Ideal para apartamento.', 'I'),
('Baleia', 'fêmea', 'grande', 'adulto', 'branco e preto', 'Splat', 'Sobradinho, Brasília, DF', 'Resgatada das ruas, muito grata e amorosa com todos.', 'D'),
('Cacau', 'fêmea', 'médio', 'filhote', 'chocolate', 'Vira-lata', 'Santa Maria, Brasília, DF', 'Curiosa e adora explorar o quintal. Já está vermifugada.', 'D'),
('Chico', 'macho', 'pequeno', 'adulto', 'creme', 'Chihuahua', 'Cruzeiro, Brasília, DF', 'Apegado a um único tutor, ciumento e muito dengoso.', 'D'),
('Apollo', 'macho', 'grande', 'adulto', 'tigrado', 'Pitbull', 'Recanto das Emas, Brasília, DF', 'Muito forte, mas um doce de temperamento. Adora carinho na barriga.', 'D'),
('Bela', 'fêmea', 'médio', 'adulto', 'dourado', 'Golden Retriever', 'Lago Sul, Brasília, DF', 'Sociável com todos os humanos e animais. Ama nadar.', 'D'),
('Toby', 'macho', 'pequeno', 'idoso', 'marrom', 'Yorkshire', 'Sudoeste, Brasília, DF', 'Calmo, adaptado a apartamento, gosta de passeios curtos.', 'I'),
('Maia', 'fêmea', 'grande', 'filhote', 'preto', 'Rottweiler', 'Ceilândia, Brasília, DF', 'Filhote grandona e estabanada, precisa de adestramento básico.', 'D'),
('Simba', 'macho', 'médio', 'adulto', 'ruivo', 'Vira-lata', 'Taguatinga, Brasília, DF', 'Independente, mas muito companheiro na hora do descanso.', 'D'),
('Nala', 'fêmea', 'médio', 'adulto', 'caramelo', 'Vira-lata', 'Samambaia, Brasília, DF', 'A clássica vira-lata caramelo. Muito esperta e alerta.', 'D'),
('Marley', 'macho', 'grande', 'adulto', 'amarelo', 'Labrador', 'Vicente Pires, Brasília, DF', 'Destruidor de chinelos profissional, mas impossível ficar bravo com ele.', 'D'),
('Nina', 'fêmea', 'pequeno', 'filhote', 'malhado', 'Vira-lata', 'Paranoá, Brasília, DF', 'Encontrada em uma caixa, muito dócil e carente de atenção.', 'D'),
('Zeus', 'macho', 'grande', 'adulto', 'cinza', 'Dog Alemão', 'Lago Norte, Brasília, DF', 'Um gigante gentil. Assusta pelo tamanho, mas é extremamente manso.', 'D'),
('Yuki', 'fêmea', 'médio', 'adulto', 'branco', 'Akita', 'Águas Claras, Brasília, DF', 'Reservada com estranhos, mas extremamente leal à família.', 'D'),
('Bruce', 'macho', 'grande', 'adulto', 'preto', 'Cane Corso', 'Guará, Brasília, DF', 'Imponente e protetor. Precisa de tutor experiente com a raça.', 'I'),
('Pandora', 'fêmea', 'médio', 'adulto', 'cinza e branco', 'Husky Siberiano', 'Asa Norte, Brasília, DF', 'Adora "conversar" uivando. Muito ativa e adora o frio do ar-condicionado.', 'D'),
('Max', 'macho', 'médio', 'adulto', 'marrom e preto', 'Beagle', 'Sudoeste, Brasília, DF', 'Movido a comida. Muito farejador e brincalhão com crianças.', 'D'),
('Mia', 'fêmea', 'pequeno', 'adulto', 'tricolor', 'Vira-lata', 'Brazlândia, Brasília, DF', 'Super carinhosa, companheira para home office.', 'D'),
('Luke', 'macho', 'médio', 'filhote', 'preto', 'Vira-lata', 'Riacho Fundo, Brasília, DF', 'Irmão da Nina, brincalhão e adora morder bolinhas de tênis.', 'D'),
('Cookie', 'macho', 'pequeno', 'adulto', 'marrom claro', 'Shih Tzu', 'Asa Sul, Brasília, DF', 'Adora um colo e cafuné atrás da orelha. Muito dócil.', 'D'),
('Zeca', 'macho', 'pequeno', 'idoso', 'branco e preto', 'Vira-lata', 'Taguatinga, Brasília, DF', 'Não tem alguns dentinhos, mas come ração úmida super bem. Muito manso.', 'D'),
('Frida', 'fêmea', 'médio', 'adulto', 'preto', 'Vira-lata', 'São Sebastiao, Brasília, DF', 'Excelente companheira para caminhadas. Alerta e inteligente.', 'D'),
('Billy', 'macho', 'pequeno', 'adulto', 'branco', 'Maltês', 'Águas Claras, Brasília, DF', 'Gosta de ser o centro das atenções. Muito dócil.', 'D'),
('Loki', 'macho', 'médio', 'filhote', 'cinza', 'Vira-lata', 'Ceilândia, Brasília, DF', 'Faz jus ao nome, apronta todas mas compensa com muito amor.', 'D'),
('Kiara', 'fêmea', 'grande', 'adulto', 'caramelo', 'Boxer', 'Planaltina, Brasília, DF', 'Muito brincalhona, pula de alegria quando vê os tutores.', 'I'),
('Bidu', 'macho', 'pequeno', 'adulto', 'azul/cinza', 'Schnauzer', 'Cruzeiro, Brasília, DF', 'Alerta, late para avisar visitas, mas é muito carinhoso.', 'D'),
('Maya', 'fêmea', 'grande', 'adulto', 'preto e marrom', 'Bernese', 'Lago Sul, Brasília, DF', 'Uma ursinha de pelúcia viva. Super mansa com crianças.', 'D'),
('Chiquinho', 'macho', 'pequeno', 'filhote', 'preto', 'Vira-lata', 'Samambaia, Brasília, DF', 'Resgatado de um bueiro, agora só quer saber de dormir quentinho.', 'D'),
('Guga', 'macho', 'médio', 'adulto', 'marrom', 'Vira-lata', 'Guará, Brasília, DF', 'Adora correr no parque. Sociável com outros cães.', 'D'),
('Flor', 'fêmea', 'pequeno', 'adulto', 'branca', 'Poodle', 'Sobradinho, Brasília, DF', 'Muito dócil, ideal para idosos por ser calma.', 'D'),
('Duque', 'macho', 'grande', 'idoso', 'marrom', 'Vira-lata', 'Gama, Brasília, DF', 'Passou a vida acorrentado, agora busca um lar final com muito amor.', 'D'),
('Lila', 'fêmea', 'pequeno', 'filhote', 'creme', 'Vira-lata', 'Santa Maria, Brasília, DF', 'Adora lamber o rosto das pessoas para demonstrar afeto.', 'D'),
('Barney', 'macho', 'grande', 'adulto', 'chocolate', 'Labrador', 'Vicente Pires, Brasília, DF', 'Ama água e comer. Muito dócil com qualquer pessoa.', 'D'),
('Sasha', 'fêmea', 'grande', 'adulto', 'capa preta', 'Pastor Alemão', 'Paranoá, Brasília, DF', 'Fiel e protetora da casa. Precisa de quintal grande.', 'I'),
('Oliver', 'macho', 'pequeno', 'filhote', 'laranja', 'Vira-lata', 'Asa Norte, Brasília, DF', 'Gatinho/Cãozinho muito curioso, se adaptaria bem em apartamento.', 'D'),
('Pretinha', 'fêmea', 'médio', 'adulto', 'preto', 'Vira-lata', 'Recanto das Emas, Brasília, DF', 'Discreta e silenciosa, quase não late. Muito comportada.', 'D'),
('Rocco', 'macho', 'médio', 'adulto', 'cinza', 'Bulldog Francês', 'Sudoeste, Brasília, DF', 'Adora um sofá e ar-condicionado. Ronca um pouquinho.', 'D'),
('Clara', 'fêmea', 'grande', 'filhote', 'branco', 'Vira-lata', 'Ceilândia, Brasília, DF', 'Vai ficar de porte grande. Muito dócil e brincalhona.', 'D'),
('Simão', 'macho', 'pequeno', 'adulto', 'caramelo', 'Pinscher', 'Taguatinga, Brasília, DF', 'Tremelique puro, mas ama um colo quente.', 'D'),
('Meg', 'fêmea', 'pequeno', 'idoso', 'tricolor', 'Fox Paulistinha', 'Guará, Brasília, DF', 'Apesar da idade, ainda é ativa e caçadora de lagartixas.', 'D'),
('Floquinho', 'macho', 'pequeno', 'adulto', 'branco', 'Bichon Frisé', 'Águas Claras, Brasília, DF', 'Parece uma nuvem. Super dócil e adora colo.', 'D'),
('Tyson', 'macho', 'grande', 'adulto', 'preto', 'Pitbull', 'Samambaia, Brasília, DF', 'Super dócil com pessoas, mas prefere ser o único animal da casa.', 'D'),
('Jade', 'fêmea', 'médio', 'adulto', 'marrom tigrado', 'Vira-lata', 'Planaltina, Brasília, DF', 'Muito carinhosa, companheira de todas as horas.', 'D'),
('Odin', 'macho', 'grande', 'adulto', 'branco e cinza', 'Samoieda', 'Lago Norte, Brasília, DF', 'Sempre parece estar sorrindo. Gosta de escovação diária.', 'I'),
('Cuca', 'fêmea', 'pequeno', 'filhote', 'preto e canela', 'Dachshund', 'Asa Sul, Brasília, DF', 'Famosa "salsichinha", adora entrar debaixo das cobertas.', 'D'),
('Baco', 'macho', 'grande', 'adulto', 'Preto', 'Rottweiler', 'Sobradinho, Brasília, DF', 'Treinado, muito obediente e equilibrado.', 'D'),
('Zelda', 'fêmea', 'médio', 'filhote', 'branca e preta', 'Vira-lata', 'Gama, Brasília, DF', 'Muito expressiva, aprende comandos rápido.', 'D'),
('Pingo', 'macho', 'pequeno', 'adulto', 'caramelo', 'Vira-lata', 'Santa Maria, Brasília, DF', 'Pequeno, cabe em qualquer cantinho e no seu coração.', 'D'),
('Julieta', 'fêmea', 'pequeno', 'adulto', 'branco', 'Maltês', 'Cruzeiro, Brasília, DF', 'Parceira do Romeu, muito dócil e calma.', 'D'),
('Romeu', 'macho', 'pequeno', 'adulto', 'branco', 'Maltês', 'Cruzeiro, Brasília, DF', 'Parceiro da Julieta, adora passear de coleira.', 'D'),
('Kira', 'fêmea', 'grande', 'idoso', 'marrom', 'Vira-lata', 'Vicente Pires, Brasília, DF', 'Célia e calma, só quer um cantinho confortável para se aposentar.', 'D'),
('Bono', 'macho', 'médio', 'filhote', 'chocolate', 'Vira-lata', 'Paranoá, Brasília, DF', 'Muito sapecha, adora correr atrás de outros cães.', 'D'),
('Cora', 'fêmea', 'médio', 'adulto', 'bege', 'Vira-lata', 'Brazlândia, Brasília, DF', 'Resgatada de maus-tratos, precisa de paciência e muito amor.', 'D'),
('Tango', 'macho', 'médio', 'adulto', 'preto e branco', 'Boston Terrier', 'Asa Norte, Brasília, DF', 'Muito engraçado e expressivo, adora crianças.', 'D'),
('Slinky', 'macho', 'pequeno', 'adulto', 'marrom', 'Dachshund', 'Sudoeste, Brasília, DF', 'Adora caçar brinquedos e é muito apegado aos donos.', 'D'),
('Madonna', 'fêmea', 'médio', 'adulto', 'loiro', 'Vira-lata', 'Taguatinga, Brasília, DF', 'Vaidosa, adora um banho e ficar cheirosa.', 'D'),
('Rambo', 'macho', 'grande', 'adulto', 'preto', 'Pastor Belga', 'Ceilândia, Brasília, DF', 'Excelente cão de guarda, muito focado e inteligente.', 'D'),
('Lilica', 'fêmea', 'pequeno', 'idoso', 'branco e marrom', 'Vira-lata', 'Guará, Brasília, DF', 'Uma senhorinha muito fofa que adora dormir no sol.', 'I'),
('Chico', 'macho', 'médio', 'adulto', 'cinza', 'Vira-lata', 'Samambaia, Brasília, DF', 'Parceiro para toda obra, super adaptável.', 'D'),
('Paçoca', 'macho', 'pequeno', 'filhote', 'caramelo claro', 'Vira-lata', 'Águas Claras, Brasília, DF', 'Mistura de fofura com energia, adora atenção.', 'D'),
('Guga', 'macho', 'grande', 'adulto', 'dourado', 'Golden Retriever', 'Lago Sul, Brasília, DF', 'Ama todo mundo. Zero agressividade.', 'D'),
('Melinda', 'fêmea', 'pequeno', 'adulto', 'preto', 'Shih Tzu', 'Asa Sul, Brasília, DF', 'Muito dócil, adora lacinhos e escovação.', 'D'),
('Pluto', 'macho', 'médio', 'adulto', 'amarelo', 'Vira-lata', 'Planaltina, Brasília, DF', 'Orelhudo e simpático, parece o cachorro dos desenhos animados.', 'D'),
('Atena', 'fêmea', 'grande', 'adulto', 'azul', 'Pitbull', 'Recanto das Emas, Brasília, DF', 'Porte atlético, dócil com a família e protetora.', 'D'),
('Baruk', 'macho', 'grande', 'filhote', 'preto e marrom', 'Fila Brasileiro', 'Sobradinho, Brasília, DF', 'Filhote imenso, vai precisar de espaço e Tutor firme.', 'D'),
('Brisa', 'fêmea', 'médio', 'adulto', 'branco', 'Vira-lata', 'Gama, Brasília, DF', 'Calma como uma brisa, quase não se nota sua presença de tão quieta.', 'D'),
('Tico', 'macho', 'pequeno', 'filhote', 'marrom', 'Chihuahua', 'Cruzeiro, Brasília, DF', 'Minúsculo e valente, adora ficar no colo.', 'D'),
('Teco', 'macho', 'pequeno', 'filhote', 'marrom escuro', 'Chihuahua', 'Cruzeiro, Brasília, DF', 'Irmão do Tico, um pouco mais tímido que o irmão.', 'D'),
('Pérola', 'fêmea', 'grande', 'idoso', 'branco', 'Labrador', 'Lago Norte, Brasília, DF', 'Cachorra de terapia aposentada, extremamente mansa.', 'I'),
('Frederico', 'macho', 'médio', 'adulto', 'cinza tigrado', 'Vira-lata', 'Santa Maria, Brasília, DF', 'Muito carinhoso, gosta de dar a pata.', 'D'),
('Duda', 'fêmea', 'pequeno', 'adulto', 'preto e branco', 'Vira-lata', 'Paranoá, Brasília, DF', 'Super dócil, companheira ideal para quem mora sozinho.', 'D'),
('Simba', 'macho', 'pequeno', 'adulto', 'laranja', 'Spitz Alemão', 'Sudoeste, Brasília, DF', 'Uma bolinha de pelos muito ativa e dócil.', 'D'),
('Zion', 'macho', 'grande', 'adulto', 'branco', 'Pastor Suíço', 'Asa Norte, Brasília, DF', 'Lindo e imponente, muito apegado à família.', 'D'),
('Nutella', 'fêmea', 'pequeno', 'filhote', 'marrom', 'Vira-lata', 'Vicente Pires, Brasília, DF', 'Doce como o nome diz, adora brincar com panos.', 'D'),
('Aslam', 'macho', 'grande', 'adulto', 'amarelo', 'Chow Chow', 'Taguatinga, Brasília, DF', 'Temperamento de gato: independente e silencioso. Língua azul.', 'D'),
('Cacau', 'macho', 'médio', 'idoso', 'marrom', 'Poodle', 'Guará, Brasília, DF', 'Enxerga pouco devido à idade, mas se orienta muito bem e é dócil.', 'D'),
('Buda', 'macho', 'grande', 'adulto', 'fawn', 'Bulldog Inglês', 'Águas Claras, Brasília, DF', 'Preguiçoso nível máximo. Ama um cochilo no tapete.', 'D'),
('Mimi', 'fêmea', 'pequeno', 'adulto', 'escama de tartaruga', 'Vira-lata', 'Ceilândia, Brasília, DF', 'Muito independente, excelente caçadora.', 'I'),
('Kadu', 'macho', 'médio', 'adulto', 'preto e canela', 'Pinscher Vira-lata', 'Samambaia, Brasília, DF', 'Porte médio, bem magrinho e ágil.', 'D'),
('Nena', 'fêmea', 'pequeno', 'idoso', 'cinza', 'Schnauzer', 'Asa Sul, Brasília, DF', 'Muito dócil, adora passear de carro.', 'D'),
('Teco', 'macho', 'médio', 'filhote', 'caramelo', 'Vira-lata', 'Brazlândia, Brasília, DF', 'Super ativo, pula muito alto quando está feliz.', 'D'),
('Kiara', 'fêmea', 'pequeno', 'adulto', 'branco e marrom', 'Jack Russell', 'Sudoeste, Brasília, DF', 'Não cansa nunca. Ótima para quem corre ou faz trilhas.', 'D'),
('Luffy', 'macho', 'médio', 'filhote', 'preto e branco', 'Vira-lata', 'Planaltina, Brasília, DF', 'Muito curioso, adora estragar caixas de papelão.', 'D'),
('Hulk', 'macho', 'grande', 'adulto', 'cinza escuro', 'American Bully', 'Recanto das Emas, Brasília, DF', 'Forte como o Hulk, mas o coração é de manteiga.', 'D'),
('Snoopy', 'macho', 'médio', 'adulto', 'tricolor', 'Beagle', 'Lago Norte, Brasília, DF', 'Adora uivar quando ouve sirenes, muito brincalhão.', 'D'),
('Bibi', 'fêmea', 'pequeno', 'filhote', 'creme', 'Vira-lata', 'Gama, Brasília, DF', 'Muito pequenininha, comilona e dorminhoca.', 'D'),
('Fumaça', 'macho', 'médio', 'adulto', 'cinza', 'Vira-lata', 'Sobradinho, Brasília, DF', 'Correu atrás de um motoboy e se perdeu, muito dócil.', 'D'),
('Rani', 'fêmea', 'grande', 'adulto', 'tigrado', 'Presa Canário', 'Santa Maria, Brasília, DF', 'Excelente para guarda de chácaras, muito fiel.', 'D'),
('Pipoca', 'macho', 'pequeno', 'adulto', 'branco', 'Vira-lata', 'Taguatinga, Brasília, DF', 'Muito dócil, adora pular no colo das visitas.', 'D'),
('Vitor', 'macho', 'médio', 'idoso', 'marrom', 'Vira-lata', 'Ceilândia, Brasília, DF', 'Calmo, sem dentes, dócil com idosos e crianças.', 'D'),
('Zaira', 'fêmea', 'grande', 'adulto', 'preto', 'Pastor Belga', 'Paranoá, Brasília, DF', 'Muito focada, aprende truques em minutos.', 'D'),
('Yarley', 'macho', 'pequeno', 'filhote', 'malhado', 'Vira-lata', 'Vicente Pires, Brasília, DF', 'Cheio de energia, adora morder os calcanhares de brincadeira.', 'D'),
('Azeitona', 'macho', 'pequeno', 'adulto', 'preto', 'Dachshund', 'Asa Norte, Brasília, DF', 'Muito simpático, adora pedir comida com os olhos pidões.', 'D');